language: node_js
node_js: '10'
cache: npm
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  matrix:
    secure: gREJi2PzY6g9Dhqi8tHiQHhNqEhRgyzRRDl6Nhh3TwIhnUwuo58DNvJPhmAs66VITMVO2ZiHp6/Fu38vUJEsqlj28RR3VP6JYKFRXGx/mk3CwY9yYK6Of2C340aGGoUPPrFjSx4uQrzh2WHEg5aDYgnFtQv0VitokRvhZAxMdTYUIYtJA8Z0Vf/67oPxZU4G+SwagUsg7awbLvzv3CcT86YE736n75BBfKR2+c70666QgA7LwtIZL8sInXj5J6WVnBGSBGADhQdBfbNfEaXITjwXjvXQOGQS2Ri3aAmuyvUmX2YpY/ciC35vgzmOOBp9T3QKZAD+pm+vAmwO/PATa/nzOpWM5TkU79XuRyIVrEhkmfSgFf75bfBGY0Asc43uU7Wee77qylXGdRmYZljJF0yfqMPQWigRGfzQhNClytaJJ32XP3CVR2NDPypyBlTQm92MsHFieHsqs4LxmIy0e6GpHXALnvf5yqW4hRgs0U+XKYY2QBj95ZNEBrQh7to73DX23rhMmRW1QWz/e6/KYw2YFFyuhbGm6E+htiVquEH6zIz7zrpKE1Mr7pwzBuMuOcsXta6tx2UK2cBAi8SBfBDbX+uV03Ikw++NgM2BklSRdRP0vUi0dSGjUvBAWpM6vFr0nfl9VU0otZNdAL+KA7x4RBAceLocA/ju1otkxew=
