language: node_js
node_js: '10'
cache: npm
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: xEX4Ah9dUojuRLMl5XJedqxe8KcHMESLbZdVSVcjWITwXm+nBlURhfj6Hg5k9SuuRdy6OZinUU5T33eZ/I09L5wi46JwNt5LIjVwnHdsdviDG9JJHTH1F4tNNYYNTdCmC6PIrBmbTlZdSMOR8WSN9jw3RAJBNw0aIJKkFfvxC6RNyX3JtSjkiAbSKXdPSSxrdDNhDr04zE/KpHHJL4kHQTJdTrnk/wPzTxcuqaShIrwDm3IR5+EfI1HTFTynluhO/N3FWtr0VguiKb4V43/8zwVH19835i3hwOScJBgvsSmRDT0T4ThZoopzrL4gXduIw50vQZhUucycWPDr+Ylz3LLFqcDzdYrwnvyROBvB9pqbYZF1ai3k4cOgbRefFy/YdKmhdR3zzqqxucnz8azN1udCzlM9CjLIBrClH6N17K0zILYLnuOxdSF23SWcK4BV+POyLb5PfwmfZhsxGKv+anFuUeOnICRA9zFUldiaVKx5gVyXHxMW3HbI+IBHaIkT4Xv9GyfNImvsqAKGYWzCw+ztIcSCZfPcHe3KC+0a2UF4ciGSXCfOWas9om92RLmeQaqrdSU8n7BUUhLcxvbyttwYWz4m7grjZskxmb8MX0zv5Pc5ro6Zb5w/ODSD/AghBQIriA+Xh+ceeqdtWUCgSVjE0PLdlkUL4HTNYs5gXsM=
services: mongodb