export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FORWARD_MESSAGE = 'FORWARD_MESSAGE';
export const GET_USERS_LIST = 'GET_USERS_LIST';
export const SET_USER_PULL = 'SET_USER_PULL';
export const CLEAR_MESSAGE_PULL = 'CLEAR_MESSAGE_PULL';
export const ADD_ROOM = 'ADD_ROOM';